# Generated by Django 5.2 on 2025-04-17 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='New Chat', max_length=200)),
                ('ai_model_identifier', models.CharField(choices=[('openai_gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo'), ('openai_gpt-4', 'OpenAI GPT-4'), ('openai_gpt-4-turbo', 'OpenAI GPT-4 Turbo'), ('anthropic_claude-3-opus', 'Anthropic Claude 3 Opus'), ('anthropic_claude-3-sonnet', 'Anthropic Claude 3 Sonnet'), ('anthropic_claude-3-haiku', 'Anthropic Claude 3 Haiku'), ('google_gemini-pro', 'Google Gemini Pro')], help_text='The specific AI model used for this session.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='end_call.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini')], help_text="The AI service this key is for (e.g., 'openai').", max_length=50)),
                ('encrypted_api_key', models.BinaryField(help_text='The encrypted API key.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Key',
                'verbose_name_plural': 'User API Keys',
                'unique_together': {('user', 'service_name')},
            },
        ),
    ]
