# Generated by Django 5.2 on 2025-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='ai_model_identifier',
            field=models.CharField(choices=[('openai_gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo'), ('openai_gpt-4', 'OpenAI GPT-4'), ('openai_gpt-4-turbo', 'OpenAI GPT-4 Turbo'), ('anthropic_claude-3-opus', 'Anthropic Claude 3 Opus'), ('anthropic_claude-3-sonnet', 'Anthropic Claude 3 Sonnet'), ('anthropic_claude-3-haiku', 'Anthropic Claude 3 Haiku'), ('google_gemini-pro', 'Google Gemini Pro'), ('gemini-2.5-pro-preview-03-25', 'gemini-2.5-pro-preview-03-25')], help_text='The specific AI model used for this session.', max_length=100),
        ),
    ]
